#!/usr/bin/env bash

# Build Play! framework
/usr/bin/ant -buildfile $PLAY_HOME/framework/build.xml

# Clean old tarball
rm -fr build/play-heroku.tar.gz

# Create tmp space for tar'ing
mkdir -p tmp/.play

# Add Play! framework
cp -r $PLAY_HOME/* tmp/.play
rm -fr tmp/.play/documentation/
rm -fr tmp/.play/python/
rm -fr tmp/.play/samples-and-tests/
rm -fr tmp/.play/support/

# Run tar and remove tmp space
if [ ! -d build ]; then
  mkdir build
fi

tar cvzf build/play-heroku.tar.gz -C tmp/ .play
rm -fr tmp/
