#!/usr/bin/env bash

BUILD_DIR=$PWD
PLAY_BUILD_DIR=~/release/play
PLAY_BRANCH=1.2.x
PLAY_TAG=HEAD

# Build Play! framework
cd $PLAY_BUILD_DIR
if [ "$PLAY_TAG" == "HEAD" ]; then
  git checkout $PLAY_BRANCH
  /usr/bin/ant -buildfile $PLAY_BUILD_DIR/framework/build.xml
else
  git checkout $PLAY_TAG
  /usr/bin/ant -buildfile $PLAY_BUILD_DIR/framework/build.xml -Dversion=$PLAY_TAG
fi

git checkout $PLAY_BRANCH

# Clean old tarball
cd $BUILD_DIR
rm -fr build/play-heroku.tar.gz

# Create tmp space for tar'ing
mkdir -p tmp/.play/framework/src/play

# Add Play! framework
cp -r $PLAY_BUILD_DIR/framework/dependencies.yml tmp/.play/framework
cp -r $PLAY_BUILD_DIR/framework/lib/             tmp/.play/framework
cp -r $PLAY_BUILD_DIR/framework/play*.jar        tmp/.play/framework
cp -r $PLAY_BUILD_DIR/framework/pym/             tmp/.play/framework
cp -r $PLAY_BUILD_DIR/framework/src/play/version tmp/.play/framework/src/play
cp -r $PLAY_BUILD_DIR/framework/templates/       tmp/.play/framework

# Add Play! core modules (minus testrunner)
mkdir -p tmp/.play/modules
cp -r $PLAY_BUILD_DIR/modules/console   tmp/.play/modules
cp -r $PLAY_BUILD_DIR/modules/crud      tmp/.play/modules
cp -r $PLAY_BUILD_DIR/modules/docviewer tmp/.play/modules
cp -r $PLAY_BUILD_DIR/modules/grizzly   tmp/.play/modules
cp -r $PLAY_BUILD_DIR/modules/secure    tmp/.play/modules

# Add Play! Linux executable
cp -r $PLAY_BUILD_DIR/play              tmp/.play

# Run tar and remove tmp space
if [ ! -d build ]; then
  mkdir build
fi

tar cvzf build/play-heroku.tar.gz -C tmp/ .play
rm -fr tmp/
